version: "3.8"
services:
  client:
    build:
      context: ./client
    ports:
      - "3001:3000"
    restart: always

  server:
    build:
      context: ./server
    ports:
      - "5001:5000"
    restart: always