services:
  client:
    build:
      context: ./client
    ports:
      - "3002:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
      - FAST_REFRESH=true
      - HOST=0.0.0.0
      - PORT=3000
      - REACT_APP_SERVER_URL=ws://localhost:5002
    volumes:
      - ./client:/app
      - /app/node_modules
    restart: always

  server:
    build:
      context: ./server
    ports:
      - "5002:5000"
    environment:
      - PORT=${PORT:-5000}
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}
      - SUPABASE_SERVICE_ROLE_KEY=${SUPABASE_SERVICE_ROLE_KEY}
    volumes:
      - ./server:/app
      - /app/node_modules
    restart: always
