version: "3.8"
services:
  client:
    build:
      context: ./client
    ports:
      - "3001:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
      - FAST_REFRESH=true
      - HOST=0.0.0.0
      - PORT=3000
    volumes:
      - ./client:/app
      - /app/node_modules
    restart: always

  server:
    build:
      context: ./server
    ports:
      - "5001:5000"
    environment:
      - PORT=5000
    volumes:
      - ./server:/app
      - /app/node_modules
    env_file:
      - ./server/.env
    restart: always
