version: "3.8"
services:
  client:
    image: epickid976/react-client:latest
    ports:
      - "3001:3000"
    restart: always

  server:
    image: epickid976/react-server:latest
    ports:
      - "5001:5000"
    restart: always

#services:
#  client:
#    build:
#      context: ./client
#    ports:
#      - "3001:3000"
#    restart: always
#
#  server:
#    build:
#      context: ./server
#    ports:
#      - "5001:5000"
#    restart: always